import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "개발중",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="ko" >
      <body cz-shortcut-listen="true">
        {children}
      </body>
    </html>
  );
}
